### PR TITLE
Templates: Multistep(wizard) form

### PR DESCRIPTION
**Pull request by Clarity-89**
Add a template for multistep form

Fixes https://github.com/grafana/grafana/issues/79556.

### CODE REVIEW

**Review by JoaoSilvaGrafana — COMMENTED** [review]
Template itself looks good! I have a more general question about the availability of these components. Should we make these Stepper/Steps/MultistepFormPage components available in grafana/ui for people to import? Otherwise are we asking them to copy all of these components to their own plugin to use the template like this?

**Comment by Clarity-89** [comment]
> Template itself looks good! I have a more general question about the availability of these components. Should we make these Stepper/Steps/MultistepFormPage components available in grafana/ui for people to import? Otherwise are we asking them to copy all of these components to their own plugin to use the template like this?

The Stepper component will be eventually moved to grafana/ui, but needs to be adjusted to be more generic. As for the other components, I don't think we'd add them to grafana/ui as their implementation will be quite different depending on each case. The main purpose of this template is to provide a starting point for a multistep form, since creating one from scratch is pretty complicated.

**Review by JoaoSilvaGrafana — APPROVED** [review]
Ah alright, I think this looks great anyway so I'm approving.
But as a suggestion, maybe could we put a copy button next to each of the expandable sections or inside the source code? Or for this case offer a downloadable folder with all of these files? Just wondering because there are so many files in this source code it would be really hard for someone who wanted to play with it to expand each section and copy each bit. Does not have to be for right now, can be an improvement we do later. Wdyt?

**Comment by Clarity-89** [comment]
> Ah alright, I think this looks great anyway so I'm approving. But as a suggestion, maybe could we put a copy button next to each of the expandable sections or inside the source code? Or for this case offer a downloadable folder with all of these files? Just wondering because there are so many files in this source code it would be really hard for someone who wanted to play with it to expand each section and copy each bit. Does not have to be for right now, can be an improvement we do later. Wdyt?

Yeah, that's a good idea. I was thinking about smth like that, just need to figure out how to make it work in a nice way.

**Pull request merged**
